### ISSUE TITLE
Fix code typo

### ISSUE THREAD

**Issue by Shinh18** [DOCGroup/autobuild#28]
I would like to fix this typo error
https://github.com/DOCGroup/autobuild/blob/fc95eef3e2379026e795804230b866df73995ab1/scoreboard.pl#L1442

**Comment by jwillemsen** [comment]
Please open a new pull request to fix the typo

**Comment by jwillemsen** [comment]
Thanks, fixed https://github.com/DOCGroup/autobuild/pull/29

**Comment by Shinh18** [comment]
Like I said, I wanted to fix it. You already did. 
Anyway, no problem

**Comment by jwillemsen** [comment]
Next time just open a pull request with the proposed changes
