### ISSUE TITLE
Config section not correct when using print_cmake_version

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/autobuild#56]
I used the print_cmake_version in our build, see https://buildlogs.remedy.nl/rhel75_opendds_versioned/. In the totals html there are now 3 config sections, this is not correct, it should only be one

**Comment by jwillemsen** [comment]
@iguessthislldo and @mitza-oci, can you have a look at this?

**Comment by iguessthislldo** [comment]
Yes, I've seen this in our builds before, but haven't investigated it yet because of the other CMake-related issues. Sometimes it works properly, sometimes it doesn't. I will take a look.
