### ISSUE TITLE
Move scoreboard configuration into its own repo

### ISSUE THREAD

**Issue by jwillemsen** [DOCGroup/autobuild#9]
We should split autobuild in two, let autobuild contain all scripts and utilities and create a new scoreboard repo with the configuration files for the atcd scoreboard

**Comment by mitza-oci** [comment]
This could be a good case for submodules.  If you need to have the config file repo, you'll also need the autobuild scripts to make use of those configuration files.

**Comment by jwillemsen** [comment]
Done, moved to https://github.com/DOCGroup/scoreboard
